# Generated by Django 4.2.7 on 2023-12-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pay_amount', models.FloatField()),
                ('amount_received', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('price_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='keyseed',
            name='p_timer',
            field=models.PositiveIntegerField(default=600),
            preserve_default=False,
        ),
    ]
