# Generated by Django 4.2.7 on 2023-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_invoice_p_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pay_amount', models.FloatField()),
                ('amount_received', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('price_amount', models.PositiveIntegerField()),
                ('p_timer', models.PositiveIntegerField()),
            ],
        ),
    ]
