# Generated by Django 4.2.7 on 2023-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_deletedinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinvoice',
            name='p_qrcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='p_qrcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
